### PR TITLE
Add Tailwind Minimal

### PR DESCRIPTION
**Pull request by 0ceanSlim**
does away with all the framework crap. This just uses basic tailwind executable to build css from in line html tailwind css. 

the readme in the style folder explains how to rebuild the css.

### CODE REVIEW

**Comment by utxo-one** [comment]
ok let's try but can you resolve the conflicts?

**Comment by 0ceanSlim** [comment]
The conflicts are happening because of the removed traditional css styling, Although I did catch I didn't style the actual notes themselves because they're in the javascript. But they are all styled now. Pull it and build it to see, and try to change up the styling a bit and see how much easier it is. Let me know your thoughts. 
image

**Comment by utxo-one** [comment]
thank you i think i can work with this! and probably other devs will like it better too lol

**Comment by 0ceanSlim** [comment]
Yep, all tucked away in it's own little style folder, html is much shorter, styling is way easier. Just run the tailwind watcher while you dev. <3 so happy to commit to open source freedom tech.

**Pull request merged**
